//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorrApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo_Fijo
    {
        public int flujofijoid { get; set; }
        public int usuarioid { get; set; }
        public string descripcion { get; set; }
        public decimal gasto { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public string tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
