//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorrApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo
    {
        public int flujoid { get; set; }
        public int usuarioid { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public int categoriaid { get; set; }
        public int negocioid { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Ubicacion_de_Negocio_Pequeño Ubicacion_de_Negocio_Pequeño { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
