//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorrApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvoDBEntities : DbContext
    {
        public EvoDBEntities()
            : base("name=EvoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Flujo> Flujo { get; set; }
        public virtual DbSet<Flujo_Fijo> Flujo_Fijo { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Producto_Favorito> Producto_Favorito { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Tips_Financieros> Tips_Financieros { get; set; }
        public virtual DbSet<Ubicacion_de_Negocio_Pequeño> Ubicacion_de_Negocio_Pequeño { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
    }
}
