//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorrApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int ofertaid { get; set; }
        public int productoid { get; set; }
        public int promocionid { get; set; }
        public int cantidad { get; set; }
        public decimal descuento { get; set; }
        public decimal monto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
